export const programData = [
  "BSc in Beekeeping Science and Technology",
  "BSc in Agricultural Engineering and Mechanization",
  "BSc in Food Science and Technology",
  "BSc in Agricultural and Natural Resources Economics and Business",
  "BSc in Crop Science and Technology",
  "BA in Archeology",
  "BA in Archeology and History",
  "BA in Archeology and Geography",
  "BA in Communication Studies",
  "BA in Diplomatic and Military History",
  "BA in Heritage Management",
  "BA in Art and Design",
  "BA in Theatre Arts",
  "BA in Film and Television Studies",
  "BA in Philosophy and Ethics",
  "BA in Music",
  "BA in Language Studies",
  "BA in Literature",
  "BA in History",
  "BA in History and Political Science",
  "BA in History, Cultural Heritage Management & Tourism",
  "BA with Education (CoHU)",
  "BA with Education (Chinese and English)",
  "BA in Anthropology",
  "BA in Geography and Environmental Studies",
  "BA in Political Science and Public Administration",
  "BA in Sociology",
  "BA in Statistics",
  "BA of Social Work",
  "BA in Psychology",
  "BA of Library and Information Studies",
  "BA with Education (CoSS)",
  "BSc in Chemical and Process Engineering",
  "BSc in Civil Engineering",
  "BSc in Electrical Engineering",
  "BSc in Mechanical Engineering",
  "BSc in Industrial Engineering",
  "BSc in Textile Design and Technology",
  "BSc in Textile Engineering",
  "Bachelor of Architecture",
  "BSc in Quantity Surveying",
  "BSc in Geomatics",
  "BSc in Actuarial Sciences",
  "BSc in Applied Zoology",
  "BSc in Botanical Sciences",
  "BSc in Chemistry",
  "BSc in Microbiology",
  "BSc in Molecular Biology and Biotechnology",
  "BSc in Wildlife Science and Conservation",
  "BSc with Education",
  "BSc in Petroleum Chemistry",
  "BSc in Meteorology",
  "BSc in Applied Microbiology and Chemistry",
  "BSc in Chemistry and Physics",
  "BSc in Mathematics and Statistics",
  "BSc in Computer Science",
  "BSc in Electronic Science and Communication",
  "BSc in Computer Engineering and Information Technology",
  "BSc in Telecommunications Engineering",
  "BSc in Business Information Technology",
  "BSc in Geophysics",
  "BSc in Geology and Geothermal Resources",
  "BSc in Petroleum Geology",
  "BSc in Geology",
  "BSc with Geology",
  "BSc in Engineering Geology",
  "BSc in Metallurgy and Mineral Processing Engineering",
  "BSc in Mining Engineering",
  "BSc in Petroleum Engineering",
  "BSc in Aquatic Sciences and Fisheries",
  "BA in Journalism",
  "BA in Mass Communication",
  "BA in Public Relations and Advertising",
  "Bachelor of Commerce in Accounting",
  "Bachelor of Commerce in Banking and Financial Services",
  "Bachelor of Commerce in Finance",
  "Bachelor of Commerce in Human Resources Management",
  "Bachelor of Commerce in Marketing",
  "Bachelor of Commerce in Tourism and Hospitality Management",
  "Bachelor of Business Administration (Evening Programme)",
  "Bachelor of Commerce in Procurement and Supply Chain Management",
  "BA in Economics",
  "BA in Economics and Statistics",
  "Bachelor of Education in Adult and Community Education",
  "Bachelor of Education in Commerce",
  "Bachelor of Education in Early Childhood Education",
  "Bachelor of Education in Physical Education and Sport Sciences",
  "Bachelor of Education in Psychology",
  "Bachelor of Arts in Gender Studies and Community Development",
  "Bachelor of Laws",
  "Bachelor of Arts in Law Enforcement",
  "BA in Kiswahili",
  "BA in Development Studies",
  "Bachelor of Education in Arts",
  "Bachelor of Education in Science",
  "Bachelor of Arts with Education",
  "Bachelor of Science with Education",
  "Bachelor of Arts in Disaster Risk Management",
  "Bachelor of Science in Chemistry",
]

export const getAllPrograms = () => {
  return [...programData, "Other"]
}

